version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:8.11
    working_directory: ~/work/lessons/homework2/homework2/
    steps:
      - checkout
      - restore_cache:
          keys:
            - bundles-{{ checksum "package.json"}}
      - run:
          name: install frontend requirements
          command: |
            npm install --only=dev
            npm install --only=prod
      - run: npm run build
      - save_cache:
          paths:
            - '~/work/lessons/homework2/homework2/node_modules'
          key: bundles-{{ checksum "package.json" }}
      - store_artifacts:
          path: static/js
          destination: bundles
